### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by kattjevfel** [beaumanvienna/marley#31]
There is no LICENSE file in the root dir, all I could find was this in the debian packaging files
https://github.com/beaumanvienna/marley/blob/7785dcbf27fe585c31991cb1d371e767af6638d3/debian/copyright#L6-L8
..so I'm assuming this project is GPL, but a proper LICENSE file would be much preferred.

**Comment by beaumanvienna** [comment]
Will be updated! :-) Thanks for all the feedback today, much appreciated!

**Comment by beaumanvienna** [comment]
The GPL was added to the root directory of the project in commit aea53726d124e01ab7665b0d84fd2ba71b5a6579
