### ISSUE TITLE
Sega Saturn support!

### ISSUE THREAD

**Issue by marcellmueller** [beaumanvienna/marley#40]
Seeing as Mednafen is already included it would be great to have support for Saturn.

**Comment by beaumanvienna** [comment]
I think the button config is [here](https://github.com/beaumanvienna/marley/blob/6296cc1483da5d451c0bacd2b70cf0008286b834/mednafen/src/drivers/input-default-buttons.h#L458).
The assignment from a Sega Saturn ROM to Mednafen should already be ok. Marley routes everything to Mednafen that is >50MB and does not contain "64" in the extension. 

I need to add a bios file detection. Should be easy. 

Which game do you recommend I test with?

**Comment by marcellmueller** [comment]
I always try Panzer Dragoon Zwei, because it's probably the most advanced 3d game on Saturn and Sega Rally because it's awesome. Those should run fine though, the Mednafen Saturn core is the best Saturn emu.

That's cool you're adding this, I'll need to dig out my Saturn controller and Mayflash adapter soon.

**Comment by beaumanvienna** [comment]
You could try it out right now if you teach your controller mapping in as usual with Mednafen (ALT+SHIFT 1).

Are you using cue files? I could add a function to generate a cue file automatically for mdf files.

Regarding the controller, do you have a preference as to how to map an X-box or a PS4 controller to  A, B, C, X, Y, Z?

**Comment by marcellmueller** [comment]
I use bin/cue, it's the way to go for Saturn stuff. I'm not at home this weekend so no controllers or my laptop, only brought my chromebook. Actually I compiled this last night but I didn't get a chance to mess around with it.  
  
As for controllers that is a tough one, I usually just use my Saturn controller with Mednafen but have ran into that issue with a ps4 controller.

**Comment by beaumanvienna** [comment]
What about
Square, Triangle, Circle = A, B, C
Cross, L2, R2, L1, R1 = X, Y, Z, L, R
?

**Comment by beaumanvienna** [comment]
Alright, here's the first commit: b75fd43009719b64b526ce343109e2c4998d34a7

X-Box/PS4 controller mapped to
```
Square, Triangle, Circle = A, B, C
Cross, L2, R2, L1, R1 = X, Y, Z, L, R
```
I added bios detection. In the games folder or in the bios folder (from the setup screen), Marley looks for files that have exactly 524288 bytes. It calculates a checksum for these files and, if it is matching, it copies the bios files to mednafen's firmware folder.

@marcellmueller  There is still one bug. It starts EU games, but not American games. I built in a debug output that is only active if mednafen's firmware folder is empty. I believe that I use the wrong bios for North America / EU. If you know what the right bios file is can you do a `./marley | grep debug` and let me know what the checksum is? You may have to delete the files in ~/.marley/mednafen/firmware/ beforehand. Thanks!

I also added the automatic creation of cue files. Marley is looking for files with either *.bin or *.mdf extension. If the Linux `file` command says it is a `Sega Saturn disc image` and if the corresponding cue file cannot be found, it will be created and used to launch mednafen.

**Comment by marcellmueller** [comment]
I'm getting a compiler error:

**Comment by beaumanvienna** [comment]
This is from wxWidgets. It's a troublemaker. On Ubuntu, it is known to cause issues when you have the developer packages for GTK2 and GTK3 installed at the same time. Also, when you have 32-bit and 64-bit versions installed.  Only yesterday, I had to change the [build script for WxWidgets on Gentoo](https://github.com/beaumanvienna/marley/commit/6d2d3cd2fc44180c22eed937221c39bd7a15e2fb).

FYI, under Focal, Marley will be linked against GTK3. You are on Focal, right?

If you can't get it to compile on your computer at home, let me know, and I can give you some more tips. A clean chroot is one solution. The [Debian build](https://github.com/beaumanvienna/marley/tree/master/debian) runs in a clean chroot environment for example. Did you try to compile the stand-alone version of PCSX2 on that machine? 

On a side note, I highly recommend Arch if you are into developing. It handles parallel installations very well. I'm mainly working under Manajaro, which has the power of Arch and does all the out-of-the-box for you, just like Ubuntu. Really the perfect combination. 

But back to your issue, I can also update the [PPA](https://launchpad.net/~beauman/+archive/ubuntu/marley/+packages). I'd rather close out Saturn support first, though.

**Comment by beaumanvienna** [comment]
I cross-checked the game & bios that didn't work with mednafen on yabause. It works there, however, only if I use the `mds` file. Maybe we have to review my [cue-file generator](https://github.com/beaumanvienna/marley/blob/b75fd43009719b64b526ce343109e2c4998d34a7/src/statemachine.cpp#L88).

**Comment by marcellmueller** [comment]
Been there, done that! I used Arch for almost 2 years and I am eternally grateful for everything I learned using it but I don't want to touch a bleeding edge distro anymore. Used to come home after doing an upgrade to a blank screen due to nvidia drivers and new kernels amongst other things. Been using Ubuntu Mate with i3 Window Manager for about 2 years now and don't see myself switching anytime soon.  
  
Anyways I am in school to be a web developer so I am not worried about this stuff. That said I am having dependancy issues on Ubuntu 20.04 on my Thinkpad as well I am trying to sort out but I was going to try and test this today.

**Comment by beaumanvienna** [comment]
Mate is nice! I started with Ubuntu on Edgy Eft, so I used that desktop for a long time. Good times!

I was exploring mds files yesterday and today. I added some debug code with 107b5dc9af89909a44889aad40d29f415859daf5 that opens the mds file (if supplied alongside with an mdf file) and fills a session structure. It doesn't do anything with that structure yet. I'm not quite sure where this is headed. I guess to load an mdf-image into memory. 

I managed to convert an mdf file into an iso, which I then mounted with fuseiso. I was surprised to see that an mdf file is basically an archive, much like an iso file. An easy solution would be to convert the mds/mdf to bin/cue files. More elegant would be to add native support for mds/mdf files in mednafen. This could be a little bit more work.

**Comment by marcellmueller** [comment]
Darkwater Saturn rips are generally considered very good and reliable, they are all bin/cue which makes it easy and are the most reliable ones. I have used Mednafen to play quite a bit of Saturn and had to figure this out but they are the best format for Saturn anyways imo.

**Comment by beaumanvienna** [comment]
Check out 9fa83ae, I build in mdf support. I use mdf2iso to generate a cue/bin file from an mdf file. If you could test that, too, please.

Kindly remove the reference to the Internet sites in your last post - we provide emulators here, but people have to rip for themselves legal copies. Sorry, it's the rule. You can talk about games on this issue tracker, that's fine.

How's that build coming along? Did you have the wxWidgets issue on Ubuntu Mate? There is a detection of the OS that you could take a look at: https://github.com/beaumanvienna/marley/blob/master/pcsx2/detect_gtk_flags.sh
For Focal and Gentoo, it will output `-DGTK3_API=TRUE`. 
The flags are used for the `cmake` run of pcsx2, see [here](https://github.com/beaumanvienna/marley/blob/9fa83aedaecdac59326908ed81e505e53699df05/configure.ac#L78). If this flag is not set cmake searches for GT2. You could compile pcsx2 manually and post the output of the cmake run:
```
cd pcsx2  && rm -rf build && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILTIN_PAD=ON -DBUILTIN_GS=ON `../detect_gtk_flags.sh` ..
make
```

**Comment by beaumanvienna** [comment]
@marcellmueller I installed Ubuntu Mate today, version 20.04.01. Everything was normal when I built and tested Marley... Can you be more specific as to why the build fails on your end?

**Comment by beaumanvienna** [comment]
I added one more feature to the Saturn support (or cue file handling in general): Detection of broken links in cue file, backing up existing cue files with broken references, and creating new cue files to fix broken links. Broken links in cue files may occur for example if the cue file is not case sensitive: c393dc88f2914b41b5d48d39c6e7a41fee124651
Here's a summary of what happened for the Sega Saturn support:
```
    A few words on how Marley is handling cue files: Cue files are
    detected in emu.cpp and added to the list of available games. That
    is, if the FILE reference in the cue file points to a valid file. In
    this case, only the cue file will show up in the game list. The 
    "bin" or "mdf" files are removed so that this function here does not
    need to be called. "bin" and "mdf" files only make it on the list of
    available games if they are not listed in any valid cue file.
    This here function creates a cue file. If an invalid cue file 
    exists, meaning the cue file's reference is broken,
    create_cue_file creates a backup. The original cue file is overwritten.
    If only an mdf file exists, a cue and a bin file are created.
```
