### ISSUE TITLE
Disable mouse support in PCSX2

### ISSUE THREAD

**Issue by beaumanvienna** [beaumanvienna/marley#45]
@Shoegzer I'm working on an emu bundle that has no mouse support. PCSX2 is included as 64-bit. I will disable the events and functions we discussed yesterday. If you could help with testing, it would be great. I am rebasing PCSX2 at the moment and will update [the PPA](https://launchpad.net/~beauman/+archive/ubuntu/marley) with version 0.1.7 when finished. If you like, I can notify you.

Demo video on Manjaro:
https://streamable.com/gsjezg

**Comment by Shoegzer** [comment]
@beaumanvienna Hey there I'd be happy to help you test, time permitting.  Not sure if Marley is being designed as more of a personal "scratch the itch" hobbyist project or an eventual RetroArch alternative, but either way it's nice work and holds lots of promise.  Cool stuff!

**Comment by beaumanvienna** [comment]
This ticket was opened to better understand the bug in the PCSX2 upstream version. The crash can be pinpointed to GTK3, as it does not apply to the downstream version Marley is using, which is rendering into an SDL window, not a wxWidgets/GTK3 window. Since this is a non-issue for the Marley project, I close this ticket here.
