### ISSUE TITLE
Feature request: Splash screen to credit upstream author contributions

### ISSUE THREAD

**Issue by Shoegzer** [beaumanvienna/marley#48]
This would add a one-page splash-screen the user would see upon launch of any system.  Information contained within the splash screen could include:

- Acknowledgement and "thank you" message to the upstream project
- Upstream project name and version or commit level
- Upstream project author(s) to the extent possible
- Upstream project license (GPL3, BSD, MIT etc.)
- Web link to upstream site, github/gitlab page etc., possibly with hotkey to launch browser tab with page.
- Brief technical details of the system emulated 
- Any other details the upstream author(s) wish to include

Ideally, the splash screen would always display by default, but with an option to disable except first-time use.

This feature aims to promote friendliness, cooperation and harmony between Marley and upstream source projects.  

This idea was inspired by the MAME splash screens that appear upon launch of a given system, which provide system information and other details, as shown here:

![snap](https://user-images.githubusercontent.com/12475371/98145134-ba09d180-1e98-11eb-8714-4fa687cb4b92.png)

**Comment by beaumanvienna** [comment]
addressed with 86f519b7879bce

**Comment by Shoegzer** [comment]
Fantastic!

**Comment by beaumanvienna** [comment]
https://streamable.com/hz7fwx

I have to revise the length of the splash screen. It should stay there until all files have been detected, but at least for 5 seconds. It should not show the game list if the 5 seconds are over. Currently, it works with an interrupt-based timer. I also have to look into your issue where it is recursively searching the drive and doesn't report any live signal.

**Comment by Shoegzer** [comment]
Thanks, hmm.. I was thinknig of a splash screen that would appear once a given system was launched, not upon loading Marley itself.  This would also leave more space for all detailed information as I had mentioned above.

**Comment by beaumanvienna** [comment]
For that, I will expand on the OSD message that for example, Mupen64Plus has at the beginning. So no actual screen. The launch sequence should be as swift as possible.

There will be more space for credits on Mezzanine screens. PPSSPP has one already, PCSX2 will get one, other cores may too.

**Comment by Shoegzer** [comment]
Ah okay.  Again my thought was to have the splash screen appear only the first time the core is launched, so launching retains its swiftness, but I understand.  The credits in the mezzanine screens is good too, just that the splash causes the user to (at least briefly) focus on and acknowledge the important emulation work others have done.
