### ISSUE TITLE
describe hardware requirements on Wiki

### ISSUE THREAD

**Issue by beaumanvienna** [beaumanvienna/marley#53]
- x86_64

**Comment by beaumanvienna** [comment]
@shoegzer: Would you like to give this a try in the wiki?

I know what the minimum requirements are but I couldn't describe it. Basically, a decent laptop from about five to seven years ago should do the trick. Don't know how to put that in numbers, though

**Comment by beaumanvienna** [comment]
This would be my suggestion:
https://github.com/beaumanvienna/marley/blob/master/README.md#hardware-requirements

**Comment by Shoegzer** [comment]
How does [this](https://pastebin.com/2y6rbr9i) sound?  I've tried to generalize the requirements so we don't get mired in specific system recommendations as YMMV.  As a suggestion I would retitle the section "System reuqirements" rather than "Hardware requirements" as OS is described there as well.

**Comment by beaumanvienna** [comment]
This is really good. Thank you, Sir!

**Comment by Shoegzer** [comment]
Sure thing, I'm glad it helped!

**Comment by beaumanvienna** [comment]
Do you want me to merge it over from Pastebin or do you prefer I pull it in via a PR?
Please advise. I am down with either way.

**Comment by Shoegzer** [comment]
Actually yeah, better to use GH for this, created PR https://github.com/beaumanvienna/marley/pull/55

Will that work?

**Comment by beaumanvienna** [comment]
merged #55 
this ticket can be closed
