### ISSUE TITLE
Project Management toolset

### ISSUE THREAD

**Issue by pgabettie** [beaumanvienna/marley#67]
This project currently doesn't have adequate project management tools.  The projects tab is unavailable, which would provide some tools, to me.  I'd need the proper permissions as an organization member.  Are you open to incorporating some other tools...like Trello and/or JIRA for instance?  I think it would keep the repository lean and clean if the team and project grow.

**Comment by pgabettie** [comment]
I think it would also be good to add a proper communications too - slack, discord, etc. to the mix for any time we might be able to link up for a live chat.

**Comment by beaumanvienna** [comment]
I added you to the repository. Hopefully, that did the trick. Please feel free to start a new project. Should we name the projects after the release number?

I'd love to have a Discord community for Marley!!

**Comment by beaumanvienna** [comment]
Here are some topics we can include in the 1st project and assign to me:
 * Wiimote support in frontend (it works already but it's not ideal yet)
 * forced update for assets in ~.marley for a newer version
 * Sega Saturn games do not launch after the very first start of Marley
 * AUR support for Marley under Arch Linux

Would you like to design a better splash screen? Are you good with GIMP?

**Comment by beaumanvienna** [comment]
When you create the first project, the current revision can be found [here](https://github.com/beaumanvienna/marley/blob/6eabea001e6470cec669fab21c791295f2835c9b/configure.ac#L5). 

Do you have an opinion on which revision the 1st official release should be? Shall we start with 1.0 and then use odd numbers after the dot for testing (1.1, 1.3) and even for release (1.2, 1.4)?

**Comment by pgabettie** [comment]
A discord server - "Marley Dev & Design" - has been setup.  Here is the invite code:
https://discord.gg/fYPKPU4DpM

On discord, friend:
Me - pgabettie#9382
JC - beaumanvienna(JC)#3974

**Comment by pgabettie** [comment]
I'll leave the versioning scheme to you, you're the developer ;)

**Comment by beaumanvienna** [comment]
@pgabettie Looks like the tools are up & running. Did you want to add anything else?

**Comment by pgabettie** [comment]
Not at this time.  We can reevaluate if growth necessitates using additional or alternative tool sets.
