### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by pgabettie** [beaumanvienna/marley#69]
A discord server - "Marley Dev & Design" - has been setup.  Here is the invite code:
https://discord.gg/fYPKPU4DpM

On discord, friend:
Me - pgabettie#9382
JC - beaumanvienna(JC)#3974

_Originally posted by @pgabettie in https://github.com/beaumanvienna/marley/issues/67#issuecomment-767724672_

**Comment by beaumanvienna** [comment]
Seems to work. Thanks a lot, man!! Closing this topic on the tracker
