### ISSUE TITLE
Blog post (Research): Design critique of PPSSPP.

### ISSUE THREAD

**Issue by pgabettie** [beaumanvienna/marley#74]
When published, will be found here: https://designprospect.com/marleyux/index.php/2021/03/07/design-critique-of-ppsspp/

**Comment by pgabettie** [comment]
1st edition posted.  Likely will be edited further and revised.

**Comment by beaumanvienna** [comment]
Let's keep this one open until the write-up is reviewed and any resulting modifications for Marley are understood

**Comment by pgabettie** [comment]
👍👍.  Rereading it I though I should add some proposed solutions as well instead merely picking it apart.

**Comment by beaumanvienna** [comment]
you want to remove this first new in "at least for new the critically important new-use"
