### ISSUE TITLE
Fix Contrast Issue with Icons

### ISSUE THREAD

**Issue by pgabettie** [beaumanvienna/marley#76]

**Comment by beaumanvienna** [comment]
addressed with 4427b58fa6b

**Comment by beaumanvienna** [comment]
@pgabettie Contrast issues fixed! Closed
334c124edbf19fbcbab3ec2c2b0ed2addd9982be
7c40a8cf2f7bc9e53af931c314414cbec054d4d3
d557838d9620bac11a23dd3326ded62adaec63d6
ddd6607f188f96d875b4213fa20348dc4025549c
