### ISSUE TITLE
native PCSX2 core

### ISSUE THREAD

**Issue by beaumanvienna** [beaumanvienna/marley#77]
@OdinVex We have a native x64 PCSX2 core in our emulator bundle. Which distro are you using? 

We provide a front-end for PCSX2, next to other emus. The front-end is all about big-picture mode and the couch experience.
The PCSX2 core is stable. It was rebased last time about six months ago.  See also https://github.com/beaumanvienna/marley#readme

**Comment by OdinVex** [comment]
> @OdinVex We have a native x64 PCSX2 core in our emulator bundle. Which distro are you using?
> 
> We provide a front-end for PCSX2, next to other emus. The front-end is all about big-picture mode and the couch experience.
> The PCSX2 core is stable. It was rebased last time about six months ago. See also https://github.com/beaumanvienna/marley#readme

Ubuntu-like (Mint) for one, EndeavourOS (Arch-like) on another. I managed to finally get a x64-compile out of PCSX2-master, but a number of things stick out (lots of graphical options are missing or changed in behavior, controller is apparently recognized by games and controls are perfect, but configuration via UI doesn't recognize any buttons of any kind), list goes on. (This is all about the native PCSX2 project, from my experience.) My shaders fail, sadly, and so games don't look as nicely as they did on my old Winedows install, but it is worth it to get away from Winedows.

Marley seems like a nice project, I never knew it existed until today, though admittedly I'm not a "Big Picture" kind of guy. I see in the Brief Look at Marley that it can toggle between fullscreen and windowed, so I'm not against it, but I've always been a fan of native UIs. I do wish I had not earlier this month thrown away a GC->USB interface, or I could have helped test some GC stuff. This Marley is looking pretty good, very nice job. :)
